app:
  # Served by the backend in production
  baseUrl: http://localhost:8080

backend:
  baseUrl: http://localhost:8080
  listen:
    port: 7007
    host: 0.0.0.0
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
